"""MonthlyTransaction table

Revision ID: 29f2bf92fa34
Revises: 
Create Date: 2023-04-23 20:21:20.801879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f2bf92fa34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_transaction',
    sa.Column('monthly_transaction_id', sa.Integer(), nullable=False),
    sa.Column('permno', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('share_type', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('monthly_transaction_id'),
    sa.UniqueConstraint('permno', 'date')
    )
    with op.batch_alter_table('monthly_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_transaction_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_transaction_permno'), ['permno'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_transaction_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_transaction_returns'), ['returns'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_transaction_share_type'), ['share_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_transaction_shares_outstanding'), ['shares_outstanding'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_shares_outstanding'))
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_share_type'))
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_returns'))
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_price'))
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_permno'))
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_exchange'))
        batch_op.drop_index(batch_op.f('ix_monthly_transaction_date'))

    op.drop_table('monthly_transaction')
    # ### end Alembic commands ###
