"""monthly transaction table

Revision ID: 6c29376253b2
Revises: 
Create Date: 2023-04-23 16:39:01.337613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c29376253b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly__transaction',
    sa.Column('monthly_transaction_id', sa.Integer(), nullable=False),
    sa.Column('permno', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('share_type', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('monthly_transaction_id'),
    sa.UniqueConstraint('permno', 'date')
    )
    with op.batch_alter_table('monthly__transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly__transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly__transaction_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly__transaction_permno'), ['permno'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly__transaction_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly__transaction_returns'), ['returns'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly__transaction_share_type'), ['share_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly__transaction_shares_outstanding'), ['shares_outstanding'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly__transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_shares_outstanding'))
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_share_type'))
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_returns'))
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_price'))
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_permno'))
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_exchange'))
        batch_op.drop_index(batch_op.f('ix_monthly__transaction_date'))

    op.drop_table('monthly__transaction')
    # ### end Alembic commands ###
